import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Vanessa's Blog - HIRE ME PLEASE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* can put navbar and constant footer or header */}
      <body className={inter.className}>
      <NavBar />
        {/* <!-- Navigation --> */}
        {/* <BrowserRouter> */}
        {/* <nav className="navbar navbar-expand-lg navbar-dark brand fixed-top">
          <div className="container">
            <Link className="navbar-brand" href="/">
              Vanessa's Blog
            </Link>
            <button
              className="navbar-toggler"
              type="button"
              data-toggle="collapse"
              data-target="#navbarResponsive"
              aria-controls="navbarResponsive"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span className="navbar-toggler-icon"></span>
            </button>
            <div className="collapse navbar-collapse" id="navbarResponsive">
              <ul className="navbar-nav ml-auto">
                <li className="nav-item"></li>
                <li>
                  <Link className="nav-link" href="/about">
                    About Me
                  </Link>
                </li>
              </ul>
            </div>
          </div>
        </nav> */}
        {/* </BrowserRouter> */}
        {children}
      </body>
    </html>
  );
}
